### ISSUE TITLE
Angular 1.3.15

### ISSUE THREAD

**Issue by jamime** [angular-ui/ui-calendar#266]
Do we know of any breaking changes preventing us updating to 1.3.15? If not can we see about bumping the bower.json. 

Something like:
`angular#^1.2.26 || >1.4.0-beta.0`

**Comment by joshkurz** [comment]
yeah I believe there is an issue with how the calendar plays with anvular.js and uiBootstrap with newest libraries.

**Comment by jamime** [comment]
ui-bootstrap is not a dependency of ui-calendar. I'm usining it with 1.3.15 and yet to see any isues.

**Comment by joshkurz** [comment]
its a dependency in the demo.

On Sat, May 16, 2015 at 1:30 PM, Jamie Thompson <notifications@github.com>
wrote:

> ui-bootstrap is not a dependency of ui-calendar. I'm usining it with
> 1.3.15 and yet to see any isues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-calendar/issues/266#issuecomment-102657553>
> .
>



-- 
*Josh Kurz*
www.joshkurz.net

**Comment by jamime** [comment]
I checked ui-bootstrap and it states `"angular": ">=1.3.0"` for the current version. ui-bootstrap is listed as being tested against 1.3.13. The tests pass for ui-calendar for 1.3.15 and I am currently using it without issue so far. Are there any known issues that I can investigate?

We shouldn't limit the supported version because our demo wouldn't work - but I'm happy to help fix it if needed.

**Comment by joshkurz** [comment]
I just pushed a new branch https://github.com/angular-ui/ui-calendar/tree/angular-1.3.x if you pull it down and run the demo, you will see the calendars are not rendered in the tabs. But when we take the tabs out of the picture the demo works. I have also upgraded to uiBootstrap0.13 as well. If we stayed on 0.9 it was still broken. So the issue is strange and it has to be related to the plethora of issues that have been made about calendars not rendering in hidden elements.

**Comment by jamime** [comment]
I have investigated and I believe I know why this is happening.

1. The initial tab select `renderCalender('myCalendar1')` is fired and `uiCalendarConfig.calendars` is not yet populated.

2. Subsequent tab selects `renderCalender('myCalendar1')`, `renderCalender('myCalendar2')`, `renderCalender('myCalendar3')` are fired before the DOM is populated with the new elements.
During the `uiCalendarConfig.calendars[calendar].fullCalendar('render')` call `uiCalendarConfig.calendars[calendar].is(':visible')` is checked<sup>[1][1]</sup>. This returns false because the tab switch has not yet happened.

I propose bumping the version as specified as this is an incompatibility of two third party libraries (ui-bootstrap and fullcalendar). The fix would have to go in either of the two libraries.

[1]: https://github.com/arshaw/fullcalendar/blob/a3589f6e10f93553f4a75b5b722e0e90bf4753cd/src/Calendar.js#L500

**Comment by jamime** [comment]
Please see: https://github.com/jamime/ui-calendar/blob/angular-1.3.x/demo/calendarDemo.js#L86 for more details.

**Comment by winnemucca** [comment]
@jamime  Is there a fix to the bug that you listed on May 19?

**Comment by jamime** [comment]
@winnemucca To use the latest version I added a custom resolution to my [`bower.json`](https://github.com/bower/bower.json-spec#resolutions). However, the issue is still apparent if you use both fullcalendar and ui.bootstrap. In order to fix it the full calendar render has to be triggered after the element is added to the page. It is fullcalendar that does the check to see if the calendar is visible or not.

If you are to fix this you need to ensure the element is considered `visible` before the `uiCalendarConfig.calendars[calendar].fullCalendar('render')` call is made.

**Comment by M0nter0** [comment]
With Angular 1.4.3 is also not working. 
I did a [plunker where you can reproduce it](http://plnkr.co/edit/jEI9fR5s2gBDbQ3dnA02?p=preview)
There you can also check all versions are, nowadays, latests versions
